export class MakeWebhookError extends Error {
  constructor(public readonly status: number, message: string) {
    super(`MakeWebhook ${status}: ${message}`);
    this.name = "MakeWebhookError";
  }
}

// ─── Types ────────────────────────────────────────────────────────────────────

/**
 * Payload that Make.com sends back to your webhook (outbound from Make).
 * Make scenarios can send any shape — this is the common envelope.
 */
export interface MakeWebhookInboundPayload {
  /** Arbitrary data fields forwarded by the Make scenario */
  [key: string]: unknown;
}

/**
 * Result of sendToMakeWebhook — Make returns a plain acceptance object.
 */
export interface MakeWebhookAccepted {
  /** "Accepted" when Make queued the payload */
  accepted: boolean;
  /** Raw response body from Make, if any */
  body?: unknown;
}

// ─── Standalone send function ─────────────────────────────────────────────────

/**
 * Send a JSON payload to a Make.com Custom Webhook URL.
 *
 * Make.com webhooks accept any POST body — no API key required.
 * The receiving scenario is triggered immediately.
 *
 * @param webhookUrl  The webhook URL generated by Make's "Custom Webhook" module.
 * @param data        Any JSON-serialisable payload.
 * @param fetchFn     Optional fetch override (for testing).
 */
export async function sendToMakeWebhook(
  webhookUrl: string,
  data: unknown,
  fetchFn: typeof fetch = globalThis.fetch,
): Promise<MakeWebhookAccepted> {
  const res = await fetchFn(webhookUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });

  if (!res.ok) {
    let message = res.statusText;
    try {
      const text = await res.text();
      if (text) message = text;
    } catch {
      // ignore
    }
    throw new MakeWebhookError(res.status, message);
  }

  let body: unknown;
  try {
    body = await res.json();
  } catch {
    // Make returns plain "Accepted" text on some plans
    try {
      body = await res.text();
    } catch {
      // ignore
    }
  }

  return { accepted: true, body };
}

// ─── Parse incoming Make payload ──────────────────────────────────────────────

/**
 * Parse and validate a payload received FROM a Make.com scenario.
 *
 * Make sends whatever data your scenario maps — this helper normalises it
 * to a typed object and rejects obviously invalid inputs.
 *
 * @throws {TypeError} if body is null, not an object, or is an array.
 */
export function parseMakeWebhookPayload(
  body: unknown,
): MakeWebhookInboundPayload {
  if (body === null || body === undefined) {
    throw new TypeError("parseMakeWebhookPayload: body is null or undefined");
  }
  if (typeof body !== "object" || Array.isArray(body)) {
    throw new TypeError(
      `parseMakeWebhookPayload: expected an object, got ${Array.isArray(body) ? "array" : typeof body}`,
    );
  }
  return body as MakeWebhookInboundPayload;
}

// ─── MakeWebhookClient class ──────────────────────────────────────────────────

/**
 * Wraps a specific Make.com webhook URL so you don't have to pass it on
 * every call. Useful when a single edge function always sends to the same
 * Make scenario.
 *
 * Example:
 *   const make = new MakeWebhookClient(Deno.env.get("MAKE_WEBHOOK_URL")!);
 *   await make.send({ event: "call.analyzed", data: { disposition: "Appointment Set" } });
 */
export class MakeWebhookClient {
  constructor(
    private readonly webhookUrl: string,
    private readonly fetchFn: typeof fetch = globalThis.fetch,
  ) {}

  /**
   * Send a payload to the webhook URL this client was constructed with.
   */
  send(data: unknown): Promise<MakeWebhookAccepted> {
    return sendToMakeWebhook(this.webhookUrl, data, this.fetchFn);
  }

  /**
   * Parse an inbound payload from Make (convenience re-export).
   */
  parseInbound(body: unknown): MakeWebhookInboundPayload {
    return parseMakeWebhookPayload(body);
  }
}
